#### WALLPAPER  ####
bind = $mainMod SHIFT, F, exec, waypaper --random
#### SCREENSHOT ####
bind = SUPER SHIFT, S, exec, ~/.dotfiles/scripts/screenshots/basic.sh
bind = $mainMod SHIFT, P, exec, ~/.config/rofi/extras/powerstyle/powerstyle.sh
bind = SUPER, L, exec, hyprlock 
### OTHERS ### 
bind = $mainMod SHIFT, w, exec, killall -SIGUSR1 waybar
bind = $mainMod, n, exec, swaync-client -t -sw
bind = $mainMod SHIFT, n, exec, rofi-wifi-menu.sh
bind = $mainMod, E, exec, rofi -show emoji -no-show-icons
