bind = $mainMod, G, exec, ~/.dotfiles/scripts/rofi/websearch.sh
bind = $mainMod SHIFT, E, exec, ~/.config/rofi/extras/powermenu/powermenu.sh
bind = $mainMod SHIFT, A, exec, ~/.dotfiles/scripts/switch-audio.sh
bind = $mainMod SHIFT, C, exec, cliphist list | rofi -dmenu -no-show-icons -font "Hasklug Nerd Font 9" | cliphist decode | wl-copy
