#### WALLPAPER  ####
bind = $mainMod SHIFT, F, exec, waypaper --random
#### SCREENSHOT ####
bind = SUPER SHIFT, S, exec, ~/.dotfiles/scripts/screenshots/basic.sh
bind = SUPER SHIFT, C, exec, ~/.dotfiles/common/.config/hypr/themes/bar/waybar/custom/colorpicker.sh
bind = SUPER SHIFT, C, exec, ~/.dotfiles/common/.config/hypr/themes/bar/waybar/custom/colorpicker.sh
bind = $mainMod SHIFT, P, exec, ~/.config/rofi/extras/powerstyle/powerstyle.sh
bind = SUPER, L, exec, hyprlock 
### OTHERS ### 
bind = $mainMod SHIFT, w, exec, killall -SIGUSR1 waybar
bind = $mainMod, n, exec, swaync-client -t -sw
bind = $mainMod SHIFT, n, exec, ~/Documentos/Tools/rofi-wifi-menu/rofi-wifi-menu.sh
bind = $mainMod, E, exec, rofi -show emoji -no-show-icons
bind = $mainMod SHIFT, T, fullscreen

bind = SUPER SHIFT, M, exec, ~/.dotfiles/scripts/hyprland/music_setup.sh
