bind = $mainMod SHIFT, E, exec, ~/.config/rofi/extras/powermenu/powermenu.sh
bind = $mainMod, G, exec, ~/.config/rofi/extras/quickweb/quickweb.sh
bind = $mainMod SHIFT, A, exec, ~/.config/rofi/extras/audio_selector/audio_selector.sh
bind = $mainMod SHIFT, C, exec, cliphist list | rofi -dmenu -no-show-icons -font "Hasklug Nerd Font 9" | cliphist decode | wl-copy

