# Gruvbox Darker

foreground              #ebdbb2
background              #1d2021

selection_foreground    #1b1b1b
selection_background    #d5c4a1
cursor                  #ebdbb2
cursor_text_color       #1b1b1b

cursor_trail_start_treshold 0
cursor_trail_decay 0.03 0.07
cursor_shape block
cursor_blink true

url_color               #83a598

active_border_color     #fabd2f
inactive_border_color   #3a3530
bell_border_color       #fe8019

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #1b1b1b
active_tab_background   #fabd2f
inactive_tab_foreground #ebdbb2
inactive_tab_background #181818
tab_bar_background      #181818

mark1_foreground #1b1b1b
mark1_background #83a598
mark2_foreground #1b1b1b
mark2_background #d3869b
mark3_foreground #1b1b1b
mark3_background #8ec07c


color0  #1d2021
color8  #665c54

color1  #fb4934
color9  #cc241d

color2  #98971a
color10 #b8bb26

color3  #d79921
color11 #fabd2f

color4  #458588
color12 #83a598

color5  #b16286
color13 #d3869b

color6  #689d6a
color14 #8ec07c

color7  #a89984
color15 #ebdbb2

background_opacity 0.80
