vim.lsp.enable("lua_ls")
vim.lsp.enable("qmlls")
vim.lsp.enable("ts_ls")
vim.lsp.enable("gopls")
vim.lsp.enable("cssls")
vim.lsp.enable("basedpyright")
vim.lsp.enable("vue_ls")
vim.lsp.enable("vtsls")
