# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
windowrule {
  name = allways-float
  match:class = yad|ristretto|waypaper|org.gnome.Calculator|blueman|protonvpn-app|blueman-manager|nm-connection-editor|pavucontrol-qt|vlc

  float = on
}

windowrule {
  name = float-small
  match:class = nm-connection-editor|protonvpn-app|blueman-manager|vlc

  size = 400x500
}

layerrule = blur on, match:namespace agsbar

layerrule {
  name = no_anim_for_selection
  blur = on
  match:namespace = agsbar
  blur_popups = on
}
layerrule {
    name = no_naim
    match:class = slurp
    no_anim = on
}

layerrule {
  name = add-blur
  match:class = wofi|eww|tofi|Tofi|eww-volume|mako|swaync|swaync-client

  blur = on
}

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrulev2 = no_focus on,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrulev = workspace special, class:(xwaylandvideobridge)



windowrule = opacity 0.9 override 0.9 override 1.0 override, match:class nemo
windowrule = opacity 0.9 override 0.9 override 1.0 override, match:class org.kde.dolphin
windowrule = opacity 0.9 override 0.9 override 1.0 override, match:class org.kde.krusader
windowrule = opacity 0.9 override 0.9 override 1.0 override, match:class org.kde.krusader
windowrule = opacity 0.80 override 0.9 override 1.0 override, match:class Spotify
windowrule = opacity 0.95 override 0.95 override 1.0 override, match:class DBeaver
windowrule = opacity 0.85 override 0.85 override 1.0 override, match:class Code
windowrule = opacity 0.95 override 0.95 override 1.0 override, match:class jetbrains-studio
windowrule = opacity 0.95 override 0.95 override 1.0 override, match:class jetbrains-idea-ce
windowrule = opacity 0.95 override 0.95 override 1.0 override, match:class ^(Tomekeeper)$

# Disable animations for specific Eww layer surfaces

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

layerrule = blur on, match:class swaync-control-center
layerrule = blur on, match:class swaync-notification-window

# layerrule = ignorezero, swaync-control-center
# layerrule = ignorezero, swaync-notification-window

layerrule = ignore_alpha 0.5, match:class swaync-control-center
layerrule = ignore_alpha 0.5, match:class swaync-notification-window

# layerrule = blur on,match:class rofi
windowrule {
  name = animate-rofi
  match:class = rofi

  # move = 100 100
  animation = popin
}


bezier = overshoot, 0.05, 0.9, 0.1, 1.1

animation = layersIn, 1, 4, overshoot, popin 40%
animation = layersOut, 1, 1, default, popin 0%
# animation = layersIn, 1, 8, default, popin 80%



windowrule = match:class spotify, workspace special:spotify
windowrule = match:class obisdian, workspace special:notes
windowrule = match:class postman, workspace special:postman

