workspace = 1, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:true
workspace = 2, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false
workspace = 3, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false
workspace = 4, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false
workspace = 5, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false
workspace = 6, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false
workspace = 7, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false
workspace = 8, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false
workspace = 9, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false
workspace = 10, monitor:desc:Philips Consumer Electronics Company PHL 271V8 0x0000A8BE, default:false

workspace = 11, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:true
workspace = 12, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false
workspace = 13, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false
workspace = 14, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false
workspace = 15, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false
workspace = 16, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false
workspace = 17, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false
workspace = 18, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false
workspace = 19, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false
workspace = 20, monitor:desc:Philips Consumer Electronics Company PHL 243V7 0x00009A4C, default:false

workspace = 1, monitor:eDP-1, default:true

workspace = special:spotify, on-created-empty:foot
workspace = special:notes, on-created-empty:foot
workspace = special:postman, on-created-empty:foot
