foreground #eceff4
background #2e3440
selection_foreground #2e3440
selection_background #88c0d0
cursor #88c0d0
cursor_text_color #2e3440
url_color #88c0d0
active_border_color #88c0d0
inactive_border_color #4c566a
bell_border_color #ebcb8b
active_tab_foreground #2e3440
active_tab_background #88c0d0
inactive_tab_foreground #d8dee9
inactive_tab_background #3b4252
tab_bar_background #242933
mark1_foreground #2e3440
mark1_background #88c0d0
mark2_foreground #2e3440
mark2_background #b48ead
mark3_foreground #2e3440
mark3_background #a3be8c
color0 #3b4252
color1 #bf616a
color2 #a3be8c
color3 #ebcb8b
color4 #81a1c1
color5 #b48ead
color6 #88c0d0
color7 #e5e9f0
color8 #4c566a
color9 #bf616a
color10 #a3be8c
color11 #ebcb8b
color12 #81a1c1
color13 #b48ead
color14 #8fbcbb
color15 #eceff4
