source = ~/.config/hypr/custom/colors.conf

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = $border_active 
    col.inactive_border = $border_inactive
    resize_on_border = false
    allow_tearing = false
    layout = scrolling
}

decoration {
    rounding = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 3
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 4
        passes = 3
        vibrancy = 0.8
        ignore_opacity = true
        noise = 0.04
        contrast = 1.5
        xray = false
    }
}


dwindle {
    pseudotile = false  
    preserve_split = true 
    force_split = 2
}

master {
  orientation = center
  slave_count_for_center_master = 0  
  always_keep_position = false
  smart_resizing = false
  drop_at_cursor = false
  mfact = 0.50
}

scrolling {

}

misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}
