exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = cliphist wipe
# exec-once = hyprpaper &
exec-once = swww-daemon &
exec-once = pypr &
# exec-once = waypaper --random &
exec-once = systemctl --user start hyprpolkitagent
# exec-once = gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-frappe-mauve-standard+default"
# exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"  # or 'prefer-light'
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = swayosd-server &
exec-once = hypridle &
exec-once = "bash -c 'playerctl metadata artist && playerctl metadata title'"
exec-once = udiskie --tray --notify &
# exec-once = swaync &
exec-once = awww-daemon &

# exec-once = export GTK_THEME=""
# exec-once = export QT_QPA_PLATFORMTHEME=gtk2

exec-once = hyprdynamicmonitors --disable-power-events &
