preload = /home/ndrolp/Pictures/Wallpapers/alena-aenami-noctilusent-1k.jpg
wallpaper = DP-4,/home/ndrolp/Pictures/Wallpapers/alena-aenami-noctilusent-1k.jpg,cover
preload = /home/ndrolp/Pictures/Wallpapers Vertical/1.jpg
wallpaper = DP-5,/home/ndrolp/Pictures/Wallpapers Vertical/1.jpg,contain
