general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 270
    on-timeout = notify-send "Your pc will suspend in 30 seconds"
}
