 # bind = $mainMod, T, exec, pypr toggle term && hyprctl dispatch bringactivetotop
bind = $mainMod, W, exec, pypr toggle wifi && hyprctl dispatch bringactivetotop

bind = $mainMod, T, exec, pypr toggle term && hyprctl dispatch bringactivetotop


windowrule {
 name = scratchpads-float
 match:class = match:class:^(scratchpad|pavucontrol|scratchtop)$

 workspace = special
 center = on silent
 size = 60% 45%
}
