map ctrl+s>n new_tab
map ctrl+s>h previous_tab
map ctrl+s>l next_tab
map ctrl+s>x close_tab
map ctrl+s>r set_tab_title
map ctrl+s>1 goto_tab 1
map ctrl+s>2 goto_tab 2
map ctrl+s>3 goto_tab 3
map ctrl+s>4 goto_tab 4
map ctrl+s>5 goto_tab 5
map ctrl+s>6 goto_tab 6
map ctrl+s>7 goto_tab 7
map ctrl+s>8 goto_tab 8
map ctrl+s>9 goto_tab 9
map ctrl+s>o close_other_tabs_in_os_window
map ctrl+s>f quick-access-terminal


