include ./colors.conf
# vim:ft=kitty

## name:     Catppuccin Kitty Macchiato
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/macchiato.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors

# ==================================================================================================

disable_ligatures cursor
font_size        9
window_padding_width 3
background_opacity 0.80
#font_family      FiraCode Nerd Font Mono
font_family     Hasklug Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
enable_audio_bell no

allow_remote_control yes


# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME