# vim:ft=kitty

## name:     Catppuccin Kitty Macchiato
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/macchiato.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors

# ==================================================================================================

disable_ligatures cursor
font_size        10
window_padding_width 3
background_opacity 0.80
font_family      GeistMono Nerd Font Mono
#font_family     Hasklug Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
enable_audio_bell no
cursor_trail 3
cursor_trail_decay 0.1 0.4

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"
tab_bar_edge top
tab_bar_align center
tab_separator " "
tab_bar_style fade
tab_powerline_style slanted
tab_fade 1 1


allow_remote_control yes

#===================================================================================================
map ctrl+alt+l next_tab
map ctrl+alt+h previous_tab
map ctrl+alt+i rename_tab
map ctrl+alt+r set_tab_title

map f1 select_tab
map ctrl+f2 detach_window
map ctrl+f3 detach_window new-tab
map ctrl+f3 detach_window tab-prev
map ctrl+f3 detach_window tab-left
map ctrl+f3 detach_window new-tab-left
map ctrl+f4 detach_window ask




# BEGIN_KITTY_THEME
# Catppuccin
include current-theme.conf
# END_KITTY_THEME
